# _config.yml

# Setup
title:               "Pi"
tagline:             'Minimal version of a blog'

# About/contact
author:
  name:              "Pi 3.1415926535.."
  url:               "https://discord.gg/vE7QUXGDnS"
  email:             "kolinchang.tw@gmail.com"
   

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
